# CircleCI configuration file

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node
    steps:
      - checkout
      - run:
          name: Install PHP dependencies
          command: composer install
      - run:
          name: Run PHPUnit tests
          command: phpunit